import "./globals.css";

export const metadata = {
  title: "voyex-admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-secondary flex items-start justify-start tracking-wide h-screen w-screen overflow-hidden">
        {children}
      </body>
    </html>
  );
}
