export const organizationPageNav = [
  {
    name: "all organizations",
    link: "/organizations",
  },
  {
    name: "active",
    link: "/organizations/active",
  },
  {
    name: "inactive",
    link: "/organizations/inactive",
  },
  {
    name: "blocked",
    link: "/organizations/blocked",
  },
];
export const allOrganizationData = [
  {
    id: "1ddwddw3",
    image: "/avatar.png",
    organization: "the brewers",
    email: "johndoe@gmail.com",
    status: "active",
    role: "-",
    plan: "-",
  },
  {
    id: "3u1reuv4",
    image: "/avatar.png",
    organization: "niker",
    email: "sofiahackmann@gmail.com",
    status: "active",
    role: "-",
    plan: "-",
  },
  {
    id: "derv1ws0",
    image: "/avatar.png",
    organization: "toyota",
    email: "jackky20@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "5kma53ae",
    image: "/avatar.png",
    organization: "pepsi",
    email: "reznov@gmail.com",
    status: "active",
    role: "organization",
    plan: "premium",
  },
  {
    id: "bhqecj4p",
    image: "/avatar.png",
    organization: "mercedes",
    email: "tommywoody@gmail.com",
    status: "inactive",
    role: "developer",
    plan: "premium+",
  },
  {
    id: "3vmnddw3",
    image: "/avatar.png",
    organization: "balenciaga",
    email: "rebeccashrishti@gmail.com",
    status: "active",
    role: "organization",
    plan: "premium+",
  },
  {
    id: "3sareuv4",
    image: "/avatar.png",
    organization: "gucci",
    email: "taara@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "degg1ws0",
    image: "/avatar.png",
    organization: "the daily",
    email: "bhavinarnav@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "5xa53ae",
    image: "/avatar.png",
    organization: "dangote",
    email: "krishnaroja@gmail.com",
    status: "inactive",
    role: "organization",
    plan: "premium+",
  },
  {
    id: "befecj4p",
    image: "/avatar.png",
    organization: "cipla",
    email: "tobisiolu@gmail.com",
    status: "inactive",
    role: "organization",
    plan: "premium+",
  },
];
