export const userPageNav = [
  {
    name: "all users",
    link: "/users",
  },
  {
    name: "active",
    link: "/users/active",
  },
  {
    name: "inactive",
    link: "/users/inactive",
  },
  {
    name: "blocked",
    link: "/users/blocked",
  },
];
export const allUsersData = [
  {
    id: "1ddwddw3",
    image: "/avatar.png",
    user: "john doe",
    email: "johndoe@gmail.com",
    status: "active",
    role: "-",
    plan: "-",
  },
  {
    id: "3u1reuv4",
    image: "/avatar.png",
    user: "sofia hackmann",
    email: "sofiahackmann@gmail.com",
    status: "active",
    role: "-",
    plan: "-",
  },
  {
    id: "derv1ws0",
    image: "/avatar.png",
    user: "jack roger",
    email: "jackky20@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "5kma53ae",
    image: "/avatar.png",
    user: "richtovic reznov",
    email: "reznov@gmail.com",
    status: "active",
    role: "organization",
    plan: "premium",
  },
  {
    id: "bhqecj4p",
    image: "/avatar.png",
    user: "Tom Wood",
    email: "tommywoody@gmail.com",
    status: "inactive",
    role: "developer",
    plan: "premium+",
  },
  {
    id: "3vmnddw3",
    image: "/avatar.png",
    user: "rebecca shrishti",
    email: "rebeccashrishti@gmail.com",
    status: "active",
    role: "organization",
    plan: "premium+",
  },
  {
    id: "3sareuv4",
    image: "/avatar.png",
    user: "Navya Taara",
    email: "taara@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "degg1ws0",
    image: "/avatar.png",
    user: "bhavin arnav",
    email: "bhavinarnav@gmail.com",
    status: "active",
    role: "developer",
    plan: "premium",
  },
  {
    id: "5xa53ae",
    image: "/avatar.png",
    user: "krishna roja",
    email: "krishnaroja@gmail.com",
    status: "inactive",
    role: "organization",
    plan: "premium+",
  },
  {
    id: "befecj4p",
    image: "/avatar.png",
    user: "Tobi oluwasegun",
    email: "tobisiolu@gmail.com",
    status: "inactive",
    role: "organization",
    plan: "premium+",
  },
];
